app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('test/test-parse', [
    'as' => 'test_parse', 'uses' => 'TestController@testParse'
]);

Route::resource('xml-file', 'XmlFileController');
Route::resource('product', 'ProductController');
Route::resource('person', 'PersonController');
Route::get('sse', 'ServerSideEventController@index');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'reference',
        'name',
        'manufacturer',
        'price',
        'wholesale_price',
        'quantity',
        'category',
        'description'
    ];

    public function product_attributes(){
        return $this->hasMany('App\ProductAttribute');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();

        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/product/index.blade.php
@extends('layout')

@section('content')
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            Products list
        </div>
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Reference
                        </th>
                        <th>
                            Wholesale price
                        </th>
                        <th>
                            Price
                        </th>
                        <th>
                            Quantity
                        </th>
                        <th>
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($products as $product)
                        <tr>
                            <td>
                                {{ $product->id }}
                            </td>
                            <td>
                                {{ $product->name }}
                            </td>
                            <td>
                                {{ $product->reference }}
                            </td>
                            <td>
                                {{ $product->wholesale_price }}
                            </td>
                            <td>
                                {{ $product->price }}
                            </td>
                            <td>
                                {{ $product->quantity }}
                            </td>
                            <td>
                                <a class="btn btn-default" href="{{ route('product.show', $product->id) }}">Show</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            Total: {{ count($product) }}
        </div>
    </div>
</div>
@stop

resources/views/product/show.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                XML file: #{{ $xml_file->id }}
            </div>
            <div class="panel-body">
                <div class="row">
                    <dl class="dl-horizontal">
                        <dt>ID:</dt>
                        <dd>{{ $xml_file->id }}</dd>

                        <dt>Original name:</dt>
                        <dd>{{ $xml_file->original_name }}</dd>

                        <dt>File name:</dt>
                        <dd>{{ $xml_file->filename }}</dd>

                        <dt>Path:</dt>
                        <dd>{{ $xml_file->path }}</dd>

                        <dt>Status:</dt>
                        <dd>{{ $xml_file->status }}</dd>

                        <dt>Created at:</dt>
                        <dd>{{ $xml_file->created_at }}</dd>

                        <dt>Updated at:</dt>
                        <dd>{{ $xml_file->updated_at }}</dd>
                    </dl>
                </div>
            </div>
            <div class="panel-footer">
            </div>
        </div>
    </div>
@stop