app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('test/test-parse', [
    'as' => 'test_parse', 'uses' => 'TestController@testParse'
]);

Route::resource('xml-file', 'XmlFileController');
Route::resource('product', 'ProductController');
Route::resource('person', 'PersonController');
Route::get('sse', 'ServerSideEventController@index');

app/XmlFile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\XmlFileStatus;

class XmlFile extends Model
{
    protected $fillable = [
        'original_name',
        'filename',
        'path',
        'status_id'
    ];

    public function nodes(){
        return $this->hasMany('App\Node');
    }

    public function status(){
        return $this->belongsTo('App\XmlFileStatus');
    }

    public function setStatus($status){
        $this->status_id = XmlFileStatus::where('status', $status)->firstOrFail()->id;
        $this->save();
    }
}

app/Http/Controllers/XmlFileController.php
<?php

namespace App\Http\Controllers;

use App\Jobs\ParseXmlFile;
use App\XmlFile;
use App\XmlFileStatus;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\XmlFileRequest;

class XmlFileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $xml_files = XmlFile::all();

        return view('xml_file.index', compact('xml_files'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('xml_file.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(XmlFileRequest $request)
    {
        $file_name = time().'_'.str_random(10).'.xml';
        $file = $request->file('xml_file');
        $file->move(public_path('xml'), $file_name);
        $xml_file = XmlFile::create([
            'original_name' => $file->getClientOriginalName(),
            'filename' => $file_name,
            'path' => public_path('xml/'.$file_name)
        ]);

        $this->dispatch(new ParseXmlFile($xml_file));

        return redirect()->route('xml-file.show', $xml_file->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $xml_file = XmlFile::findOrFail($id);

        return view('xml_file.show', compact('xml_file'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/xml_file/create.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                Create new XML file
                <a class="btn btn-primary" href="{{ route('xml-file.create') }}">Create</a>
            </div>
            <div class="panel-body">
                @include('_errors')

                {!! Form::open([
                    'method' => 'POST',
                    'route' => 'xml-file.store',
                    'files' => true
                ]) !!}
                    <div class="form-group">
                        {!! Form::label('xml_file', 'XML file') !!}
                        {!! Form::input('file', 'xml_file', null) !!}
                    </div>

                    {!! Form::submit('submit', ['class' => 'btn btn-default']) !!}
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@stop

resources/views/xml_file/index.blade.php
@extends('layout')

@section('content')
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            XML files list
            <a class="btn btn-primary" href="{{ route('xml-file.create') }}">Create</a>
        </div>
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            Original name
                        </th>
                        <th>
                            Filename
                        </th>
                        <th>
                            Status
                        </th>
                        <th>
                            Created at
                        </th>
                        <th>
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($xml_files as $xml_file)
                        <tr>
                            <td>
                                {{ $xml_file->id }}
                            </td>
                            <td>
                                {{ $xml_file->original_name }}
                            </td>
                            <td>
                                {{ $xml_file->filename }}
                            </td>
                            <td>
                                {{ $xml_file->status }}
                            </td>
                            <td>
                                {{ $xml_file->created_at }}
                            </td>
                            <td>
                                <a class="btn btn-default" href="{{ route('xml-file.show', $xml_file->id) }}">Show</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            Total: {{ count($xml_files) }}
        </div>
    </div>
</div>
@stop

resources/views/xml_file/show.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                XML file: #{{ $xml_file->id }}
            </div>
            <div class="panel-body">
                <div class="row">
                    <dl class="dl-horizontal">
                        <dt>ID:</dt>
                        <dd>{{ $xml_file->id }}</dd>

                        <dt>Original name:</dt>
                        <dd>{{ $xml_file->original_name }}</dd>

                        <dt>File name:</dt>
                        <dd>{{ $xml_file->filename }}</dd>

                        <dt>Path:</dt>
                        <dd>{{ $xml_file->path }}</dd>

                        <dt>Created at:</dt>
                        <dd>{{ $xml_file->created_at }}</dd>

                        <dt>Updated at:</dt>
                        <dd>{{ $xml_file->updated_at }}</dd>
                    </dl>
                </div>
            </div>
            <div class="panel-footer">
            </div>
        </div>
    </div>
@stop